# ABOUTME: HTML exporter for creating self-contained reports
# ABOUTME: Generates interactive HTML with embedded CSS and visualizations

from pathlib import Path
from typing import Dict, Any
from datetime import datetime
import html

from .base import Exporter


class HTMLExporter(Exporter):
    """Export results as self-contained HTML report"""

    def get_extension(self) -> str:
        return ".html"

    def export(self, results: Dict[str, Any], output_path: Path) -> Path:
        """
        Export results as HTML report.

        Args:
            results: Dictionary with 'results', 'config', 'metadata' keys
            output_path: Path to write HTML file

        Returns:
            Path to created HTML file
        """
        # Ensure output path has correct extension
        if not output_path.suffix:
            output_path = output_path.with_suffix(self.get_extension())

        # Ensure parent directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Extract data
        run_results = self._flatten_results(results['results'])
        config = results.get('config', {})
        metadata = self._format_metadata(results.get('metadata', {}))

        # Generate HTML
        html_content = self._generate_html(run_results, config, metadata)

        # Write to file
        output_path.write_text(html_content)
        return output_path

    def _generate_html(self, results: Dict[str, Any], config: Dict[str, Any], metadata: Dict[str, Any]) -> str:
        """Generate complete HTML document"""

        # Generate sections
        summary_html = self._generate_summary_section(results, metadata)
        strategies_html = self._generate_strategies_section(results)
        quality_html = self._generate_quality_section(results)
        timeline_html = self._generate_timeline_section(results)
        config_html = self._generate_config_section(config)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Garbling Economics - Run Report</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🎮 Garbling Economics Game Report</h1>
            <p class="subtitle">Bayesian Persuasion & Information Design Simulation</p>
        </header>

        {summary_html}
        {strategies_html}
        {quality_html}
        {timeline_html}
        {config_html}

        <footer>
            <p>Generated by <strong>garbling-gym</strong> on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
            <p>Git commit: <code>{html.escape(str(metadata.get('git_commit') or 'Unknown'))}</code></p>
        </footer>
    </div>
</body>
</html>"""

    def _generate_summary_section(self, results: Dict[str, Any], metadata: Dict[str, Any]) -> str:
        """Generate summary statistics section"""
        return f"""
        <section class="summary">
            <h2>📊 Summary</h2>
            <div class="metadata">
                <p><strong>Run Name:</strong> {html.escape(metadata.get('name', 'Unnamed'))}</p>
                <p><strong>Timestamp:</strong> {metadata.get('timestamp', 'Unknown')}</p>
                <p><strong>Duration:</strong> {metadata.get('duration', 0):.2f}s</p>
                <p><strong>Tags:</strong> {', '.join(metadata.get('tags', [])) or 'None'}</p>
            </div>

            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">{results['total_rounds']}</div>
                    <div class="metric-label">Total Rounds</div>
                </div>
                <div class="metric-card sender">
                    <div class="metric-value">{results['sender_total']:+.0f}</div>
                    <div class="metric-label">Sender Total</div>
                </div>
                <div class="metric-card receiver">
                    <div class="metric-value">{results['receiver_total']:+.0f}</div>
                    <div class="metric-label">Receiver Total</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{results['buy_rate']:.1%}</div>
                    <div class="metric-label">Buy Rate</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{results['avg_informativeness']:.2f}</div>
                    <div class="metric-label">Avg Informativeness</div>
                </div>
                <div class="metric-card warning">
                    <div class="metric-value">{results['receiver_regret']:+.0f}</div>
                    <div class="metric-label">Receiver Regret</div>
                </div>
            </div>

            <div class="welfare-analysis">
                <h3>Economic Welfare Analysis</h3>
                <p><strong>Total Social Welfare:</strong> {results['sender_total'] + results['receiver_total']:+.0f}</p>
                <p><strong>Perfect Info Benchmark:</strong> {results.get('perfect_info_benchmark', 0):+.0f}</p>
                <p><strong>Deadweight Loss:</strong> {results.get('perfect_info_benchmark', 0) - results['receiver_total']:+.0f}</p>
                <p class="insight">💡 Garbling transfers value from receiver to sender and creates inefficiency.</p>
            </div>
        </section>
        """

    def _generate_strategies_section(self, results: Dict[str, Any]) -> str:
        """Generate strategy usage section"""
        strategies = results.get('strategies_used', {})
        total = results['total_rounds']

        if not strategies:
            return ""

        rows = []
        for strategy, count in sorted(strategies.items(), key=lambda x: -x[1]):
            pct = count / total * 100 if total > 0 else 0
            bar_width = int(pct)
            rows.append(f"""
                <tr>
                    <td>{html.escape(strategy)}</td>
                    <td>{count}</td>
                    <td>{pct:.1f}%</td>
                    <td>
                        <div class="bar-container">
                            <div class="bar" style="width: {bar_width}%"></div>
                        </div>
                    </td>
                </tr>
            """)

        return f"""
        <section class="strategies">
            <h2>🎯 Strategy Distribution</h2>
            <table>
                <thead>
                    <tr>
                        <th>Strategy</th>
                        <th>Count</th>
                        <th>Percentage</th>
                        <th>Distribution</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(rows)}
                </tbody>
            </table>
        </section>
        """

    def _generate_quality_section(self, results: Dict[str, Any]) -> str:
        """Generate quality statistics section"""
        quality_stats = results.get('quality_stats', {})

        if not quality_stats:
            return ""

        rows = []
        for quality in ['HIGH', 'MEDIUM', 'LOW']:
            stats = quality_stats.get(quality, {})
            count = stats.get('count', 0)
            bought = stats.get('bought', 0)
            buy_rate = stats.get('buy_rate', 0)
            sender_total = stats.get('sender_total', 0)
            receiver_total = stats.get('receiver_total', 0)

            quality_class = quality.lower()
            rows.append(f"""
                <tr class="{quality_class}">
                    <td><strong>{quality}</strong></td>
                    <td>{count}</td>
                    <td>{bought}</td>
                    <td>{buy_rate:.1%}</td>
                    <td>{sender_total:+.0f}</td>
                    <td>{receiver_total:+.0f}</td>
                </tr>
            """)

        return f"""
        <section class="quality">
            <h2>📈 Quality Distribution & Outcomes</h2>
            <table>
                <thead>
                    <tr>
                        <th>Quality</th>
                        <th>Count</th>
                        <th>Bought</th>
                        <th>Buy Rate</th>
                        <th>Sender Total</th>
                        <th>Receiver Total</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(rows)}
                </tbody>
            </table>
        </section>
        """

    def _generate_timeline_section(self, results: Dict[str, Any]) -> str:
        """Generate round-by-round timeline"""
        history = results.get('history', [])

        if not history:
            return ""

        # Show first 20 rounds
        rows = []
        sender_cumulative = 0
        receiver_cumulative = 0

        for h in history[:20]:
            sender_cumulative += h.get('sender_payoff', 0)
            receiver_cumulative += h.get('receiver_payoff', 0)

            quality_class = h.get('quality', 'LOW').lower()
            action_class = 'bought' if h.get('action') == 'BUY' else 'passed'

            rows.append(f"""
                <tr>
                    <td>{h.get('round', 0)}</td>
                    <td class="{quality_class}">{h.get('quality', '-')}</td>
                    <td>{h.get('signal', '-')}</td>
                    <td class="{action_class}">{h.get('action', '-')}</td>
                    <td>{h.get('sender_payoff', 0):+.0f}</td>
                    <td>{h.get('receiver_payoff', 0):+.0f}</td>
                    <td>{sender_cumulative:+.0f}</td>
                    <td>{receiver_cumulative:+.0f}</td>
                    <td>{h.get('garbling_info', 0):.2f}</td>
                </tr>
            """)

        if len(history) > 20:
            rows.append("<tr><td colspan='9' class='more'>... and {} more rounds</td></tr>".format(len(history) - 20))

        return f"""
        <section class="timeline">
            <h2>⏱️ Round-by-Round Timeline</h2>
            <div class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Round</th>
                            <th>Quality</th>
                            <th>Signal</th>
                            <th>Action</th>
                            <th>S. Payoff</th>
                            <th>R. Payoff</th>
                            <th>S. Cumul.</th>
                            <th>R. Cumul.</th>
                            <th>Info</th>
                        </tr>
                    </thead>
                    <tbody>
                        {''.join(rows)}
                    </tbody>
                </table>
            </div>
        </section>
        """

    def _generate_config_section(self, config: Dict[str, Any]) -> str:
        """Generate configuration section"""
        return f"""
        <section class="config">
            <h2>⚙️ Configuration</h2>
            <div class="config-grid">
                <div class="config-item">
                    <strong>Rounds:</strong> {config.get('num_rounds', 'Unknown')}
                </div>
                <div class="config-item">
                    <strong>LLM Enabled:</strong> {config.get('use_llm', False)}
                </div>
                <div class="config-item">
                    <strong>Model:</strong> {config.get('llm_model', 'N/A')}
                </div>
            </div>

            <h3>Prior Distribution</h3>
            <div class="prior-display">
                {self._format_prior(config.get('prior', {}))}
            </div>
        </section>
        """

    def _format_prior(self, prior: Dict[str, float]) -> str:
        """Format prior distribution as HTML"""
        if not prior:
            return "<p>No prior specified</p>"

        items = []
        for quality, prob in prior.items():
            items.append(f"<div class='prior-item'><strong>{quality}:</strong> {prob:.2%}</div>")

        return ''.join(items)

    def _get_css(self) -> str:
        """Get embedded CSS styles"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #4a90e2;
            padding-bottom: 20px;
        }

        h1 {
            color: #2c3e50;
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .subtitle {
            color: #7f8c8d;
            font-size: 1.1em;
        }

        h2 {
            color: #34495e;
            margin: 30px 0 20px 0;
            padding-bottom: 10px;
            border-bottom: 2px solid #ecf0f1;
        }

        h3 {
            color: #34495e;
            margin: 20px 0 10px 0;
        }

        section {
            margin: 40px 0;
        }

        .metadata {
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .metadata p {
            margin: 5px 0;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }

        .metric-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        .metric-card.sender {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        }

        .metric-card.receiver {
            background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        }

        .metric-card.warning {
            background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
        }

        .metric-value {
            font-size: 2em;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .metric-label {
            font-size: 0.9em;
            opacity: 0.9;
        }

        .welfare-analysis {
            background: #e8f5e9;
            padding: 20px;
            border-radius: 5px;
            border-left: 4px solid #4caf50;
            margin-top: 20px;
        }

        .welfare-analysis p {
            margin: 8px 0;
        }

        .insight {
            font-style: italic;
            color: #2e7d32;
            margin-top: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        thead {
            background: #34495e;
            color: white;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        tbody tr:hover {
            background: #f5f5f5;
        }

        .bar-container {
            background: #ecf0f1;
            border-radius: 3px;
            overflow: hidden;
            height: 20px;
        }

        .bar {
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            height: 100%;
            transition: width 0.3s ease;
        }

        .high {
            background: #e8f5e9;
        }

        .medium {
            background: #fff9c4;
        }

        .low {
            background: #ffebee;
        }

        .bought {
            color: #4caf50;
            font-weight: bold;
        }

        .passed {
            color: #9e9e9e;
        }

        .table-container {
            overflow-x: auto;
        }

        .more {
            text-align: center;
            color: #7f8c8d;
            font-style: italic;
        }

        .config-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }

        .config-item {
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
        }

        .prior-display {
            display: flex;
            gap: 20px;
            margin: 15px 0;
        }

        .prior-item {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            flex: 1;
            text-align: center;
        }

        footer {
            margin-top: 60px;
            padding-top: 20px;
            border-top: 2px solid #ecf0f1;
            text-align: center;
            color: #7f8c8d;
        }

        footer code {
            background: #ecf0f1;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }

        @media print {
            body {
                background: white;
                padding: 0;
            }

            .container {
                box-shadow: none;
            }
        }
        """
